CONTIKI_PROJECT = nullnet-unicast nullnet-broadcast pregunta1 pregunta2

CONTIKI = ../..

# Use this to enable TSCH: MAKE_MAC = MAKE_MAC_TSCH
MAKE_MAC ?= MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include